#define FLOW_TAP_TERM 100
#define CHORDAL_HOLD
#define RETRO_TAPPING

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "ymAex/YnR7EQ"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 3

#define RGB_MATRIX_STARTUP_SPD 60

